---
name: Build and Push Docker Image

on:
  workflow_dispatch:
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Authenticate to AWS
        id: aws-auth
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: docker Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./nuxt-app
          push:  ${{ github.event_name == 'workflow_dispatch' }}
          platforms: linux/amd64
          file: ./nuxt-app/Dockerfile
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
