---
    name: Terraform APPLY
    
    on:
      workflow_dispatch:
      
    
    jobs:
      terraform-apply:
        runs-on: ubuntu-latest
    
        permissions:
          id-token: write
          contents: read
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            
          - name: Authenticate to AWS
            id: aws-auth
            uses: aws-actions/configure-aws-credentials@v2
            with:
              role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
              aws-region: ${{ secrets.AWS_REGION }}

          - name: who_am_i
            run: aws sts get-caller-identity
            
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: 1.5.0

          - name: Terraform Init
            run: ls
            

          - name: Terraform Apply
            run: terraform  -chdir=terraform plan -auto-approve
            env:
              TF_VAR_region: ${{ secrets.AWS_REGION }}
